In [1]:
import os
#os.environ['PYSPARK_SUBMIT_ARGS']="--jars /Users/Philip/Downloads/mysql-connector-java-5.1.46/mysql-connector-java-5.1.46.jar pyspark-shell"
#os.environ['PYSPARK_SUBMIT_ARGS']='--packages com.mysql:mysql:5.1.46 pyspark-shell'
import pyspark
from pyspark.sql import SQLContext
from pyspark import SparkFiles
from pyspark import SparkContext
from pyspark import SparkConf
#os.environ['PYSPARK_SUBMIT_ARGS']="--jars /Users/Philip/Downloads/mysql-connector-java-5.1.46/mysql-connector-java-5.1.46-bin.jar pyspark-shell"

In [2]:
sc.stop()

In [3]:
conf = SparkConf().setAppName('test') #.addJar('/Users/Philip/Downloads/mysql-connector-java-5.1.46/mysql-connector-java-5.1.46-bin.jar')

In [4]:
sc = SparkContext(conf=conf) #, pyFiles='/Users/Philip/Downloads/test.zip')
sc.addPyFile('/Users/Philip/Downloads/test.zip')
sc.addFile('/Users/Philip/Downloads/mysql-connector-java-5.1.46/mysql-connector-java-5.1.46-bin.jar')
sqlContext = SQLContext(sc)

In [104]:
jdbc_url = "jdbc:mysql://localhost:3306/nba_stats_prod?useServerPrepStmts=false&rewriteBatchedStatements=true" #?user=root&password=Sk1ttles'

In [105]:
conn_properties ={
    'user':'root',
    'password':'Sk1ttles',
    'driver':'com.mysql.jdbc.Driver'
}

In [106]:
query = '''(
select b.game_hash,
       p.player_id,
       b.team,
       b.MP as minutes_played,
       b.FG,
       b.FGA,
       b.fg_pct,
       b.3P,
       b.3PA,
       b.3p_pct,
       b.FT,
       b.ft_pct,
       b.ORB,
       b.DRB,
       b.TRB,
       b.AST,
       b.STL,
       b.BLK,
       b.TOV,
       b.PF,
       b.PTS,
       b.plus_minus
from nba_stats.basic_box_stats as b
inner join nba_stats.box_score_map as bm on b.game_hash = bm.game_hash
inner join(

     select p.player_id, name, pm.team, lu.day
     from nba_stats.player_info as p
     inner join nba_stats.player_team_map as pm on p.player_id = pm.player_id
     inner join nba_stats.game_date_lookup as lu on pm.season = lu.season

) as p on b.name = p.name and
          b.team = p.team and
          bm.game_date = p.day) as a'''

In [107]:
df = sqlContext.read.format('jdbc').options(
        driver="com.mysql.jdbc.Driver",
        url=jdbc_url,
        user='root',
        password='Sk1ttles',
        dbtable=query,
        fetchsize=10000,
        partitionColumn='player_id',
        lowerBound=2009202,
        upperBound=5363436,
        numPartitions=8).load()
#display(df)
#df.show()
#df.count()

In [61]:
pd_df = df.toPandas()

In [36]:
pd_df.count()

game_hash         706850
player_id         706850
team              706850
minutes_played    706850
FG                706850
FGA               706850
fg_pct            706850
3P                706850
3PA               706850
3p_pct            706850
FT                706850
ft_pct            706850
ORB               706850
DRB               706850
TRB               706850
AST               706850
STL               706850
BLK               706850
TOV               706850
PF                706850
PTS               706850
plus_minus        482456
dtype: int64

In [37]:
pd_df.head(20)

,game_hash,player_id,team,minutes_played,FG,FGA,fg_pct,3P,3PA,3p_pct,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,plus_minus
0,000f16fa89e2149852b5dcddd33f200a,2030189,Philadelphia 76ers,26:13,5,13,.385,1,6,.167,...,1,11,12,1,0,0,4,2,13,+5
1,0047306e314a9185a86646f3afa75bbf,2030191,Toronto Raptors,21:28,3,4,.750,0,1,0,...,2,1,3,2,1,2,2,2,7,-1
2,0049b46915affb52a244f0a19d74d37f,2015049,Cleveland Cavaliers,7:49,2,2,1,0,0,0,...,2,0,2,0,0,0,0,2,4,+1
3,00810045a55551dc26cd0d1a59dbfa23,2030190,Atlanta Hawks,38:15,8,21,.381,1,8,.125,...,2,2,4,6,1,0,1,2,23,+2
4,00f3c3e8264e231f552bdcd852dc2f6a,2030191,Toronto Raptors,9:49,0,0,0,0,0,0,...,1,3,4,0,0,1,1,5,0,+4
5,00f79d52305751eacf8414695b54c3aa,2030191,Toronto Raptors,7:13,1,1,1,0,0,0,...,1,1,2,0,0,0,1,1,4,+14
6,0107f6b0960d8cfa3ba2ccda5faafa70,2015050,Denver Nuggets,26:32,5,9,.556,3,5,.600,...,0,6,6,1,1,0,2,1,14,+11
7,01127701f2a8525e5b87340830f57c41,2015055,Boston Celtics,3:17,1,2,.500,1,1,1,...,0,1,1,0,0,0,2,2,3,+4
8,01127701f2a8525e5b87340830f57c41,2030189,Philadelphia 76ers,23:41,4,10,.400,0,4,0,...,4,6,10,2,0,1,6,5,9,+2
9,0117350ff832f278113baba1350c0d38,2015050,Denver Nuggets,11:45,1,2,.500,0,0,0,...,1,3,4,1,0,0,0,0,4,+6
10,011ae64c38ef82cfc2244a49ea4d49f8,2009202,Phoenix Suns,9:36,0,1,0,0,1,0,...,0,3,3,0,0,2,0,2,0,+10
11,011f54c954d9703c8069ed05a7feb6b9,2030190,Atlanta Hawks,28:21,6,15,.400,2,6,.333,...,0,3,3,1,0,0,1,3,18,-13
12,013e8095aeaee050df1e844d09f733b5,2015049,Cleveland Cavaliers,34:24,7,12,.583,0,0,0,...,2,8,10,0,1,1,0,3,15,-5
13,013e8095aeaee050df1e844d09f733b5,2030187,Utah Jazz,26:38,8,10,.800,0,0,0,...,3,12,15,5,2,2,3,3,19,+26
14,015ecf154d3338a2a2f0fa245b8b88ef,2030189,Philadelphia 76ers,15:06,1,10,.100,1,5,.200,...,0,3,3,1,2,0,2,0,3,-21
15,015ecf154d3338a2a2f0fa245b8b88ef,2030190,Atlanta Hawks,30:41,6,18,.333,1,2,.500,...,0,1,1,9,2,1,1,1,15,+13
16,016ad420ed140f23af3754bcb4383835,2015054,Milwaukee Bucks,20:55,4,10,.400,3,7,.429,...,2,6,8,0,0,1,2,2,11,+12
17,016ad420ed140f23af3754bcb4383835,2030188,Milwaukee Bucks,29:39,13,20,.650,1,3,.333,...,5,11,16,9,3,0,3,1,33,+27
18,017c510e22ee2e2302f2e9afe69708f5,2015050,Denver Nuggets,2:53,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,-2
19,017c510e22ee2e2302f2e9afe69708f5,2015054,Milwaukee Bucks,4:22,2,2,1,2,2,1,...,0,0,0,0,0,1,1,3,6,-2

In [95]:
df.write.format('jdbc').options(
      url='jdbc:mysql://localhost/nba_stats_test?useServerPrepStmts=false&rewriteBatchedStatements=true',
      driver='com.mysql.jdbc.Driver',
      schema='nba_stats_test',
      dbtable='basic_box_stats',
      user='root',
      password='Sk1ttles',
      batchsize=10000,
      partitionColumn='player_id',
      lowerBound=2009202,
      upperBound=5363436,
      numPartitions=8).mode('append').save()

KeyboardInterrupt:

In [101]:
sc.stop()

In [88]:
df.write.jdbc('jdbc:mysql://localhost/nba_stats_test', 'basic_box_stats', 'overwrite', conn_properties)

In [108]:
df.write.format('jdbc').options(
      url='jdbc:mysql://localhost/nba_stats_test', #?useServerPrepStmts',#=false&rewriteBatchedStatements=true',
      driver='com.mysql.jdbc.Driver',
      schema='nba_stats_test',
      dbtable='basic_box_stats',
      user='root',
      password='Sk1ttles',
      batchsize=10000,
      partitionColumn='player_id',
      lowerBound=2009202,
      upperBound=5363436,
      rewriteBatchedStatements=True,
      numPartitions=8).mode('overwrite').save()

In [9]:
import random
num_samples = 100000000
def inside(p):     
  x, y = random.random(), random.random()
  return x*x + y*y < 1
count = sc.parallelize(range(0, num_samples)).filter(inside).count()
pi = 4 * count / num_samples
print(pi)
sc.stop()

3.14148448

In [86]:
result = sqlContext.sql(''.join([i.strip('\n') for i in query]))

In [87]:
sc.cancelAllJobs()

In [22]:
### Running all python files in test zip

In [29]:
def run_py(file):
    os.system('python3 %s' % file)
    return

In [41]:
py_files = []
for root, dir, files in os.walk('/Users/Philip/Downloads/test'):
    for file in files: 
        py_files.append(os.path.join(root, file))

In [42]:
jobs = sc.parallelize(py_files)

In [43]:
par = jobs.map(lambda x: run_py(x))

In [45]:
par.collect()

[None, None, None]